import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import HomePage from "../components/homepage";
import Footer from "../components/footer";
import { useState, useEffect } from "react";

export default function Home() {
  const [scroll, setScroll] = useState(0);
  useEffect(() => {
    window.addEventListener("scroll", () => {
      setScroll(window.scrollY);
    }),
      [scroll];
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Viettel FTTH</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        {/* <Header scroll /> */}
        {scroll > 100 ? <Header scroll /> : ""}
        <HomePage />
        <Footer />
      </main>
    </div>
  );
}
